name: shelf_server_test
description: A new Flutter project.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  functions_framework: ^0.3.1
  shelf: ^0.7.9
  shelf_static: ^0.2.9+2
  universal_html: ^1.2.4

dev_dependencies:
  build_runner: ^1.10.2
  build_verify: ^1.1.1
  functions_framework_builder: ^0.3.1